language: ruby
cache: bundler

rvm:
  - jruby
  - 2.1.1

script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - karol.galanciak@gmail.com
    on_failure: change
    on_success: never